# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet(u"/*\n"
"blue = #002642\n"
"red = #840032\n"
"yellow = #E59500\n"
"light_gray = #E5DADA\n"
"black = #02040F\n"
"\n"
"white = #E5DADA\n"
"\n"
"gray = #f0f0f0\n"
"\n"
"light_yellow = #E59500\n"
"\n"
"background_gray = #292929\n"
"*/\n"
"\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"	background-color: #292929;\n"
"	color: #E59500;\n"
"	border: 0px;\n"
"	border-color: #E59500;\n"
"	font-family: \"MavenPro\";\n"
"}\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"	background-color: transparent;\n"
"	color: #E59500;\n"
"	font-size: 12px;\n"
"\n"
"}\n"
"\n"
"QLabel::disabled\n"
"{\n"
"	background-color: transparent;\n"
"	color: #f0f0f0;\n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar\n"
"{\n"
"	background-color: #E59500;\n"
"	color: #E5DADAE5DADA;\n"
"	border-color: #E59500;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*-----QToolTip-----*/\n"
"QToolTip\n"
"{\n"
"	border : 1px solid #000000;\n"
"	background-color: #26264f;\n"
"	color: #E5DADAE5DADA;\n"
"	border-color: #051a39;\n"
"}\n"
"\n"
"/*-----QPushB"
                        "utton-----*/\n"
"QPushButton\n"
"{\n"
"	background-color: #E59500;\n"
"	color: #002642;\n"
"	border-style: none;\n"
"	border-width: 1px;\n"
"	border-radius: 5px;\n"
"	border-color: ;\n"
"	padding: 10px;\n"
"	font:bold;\n"
"}\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"	background-color: #ffccd8;\n"
"	color: #840032;\n"
"	border-style: none;\n"
"	border-width: 1px;\n"
"	border-radius: 5px;\n"
"	border-color: ;\n"
"	padding: 10px;\n"
"	font:bold;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"	background-color: #002642;\n"
"	color: #E5DADA;\n"
"	border-style: none;\n"
"	border-width: 1px;\n"
"	border-radius: 5px;\n"
"	border-color: ;\n"
"	padding: 10px;\n"
"	font:bold;\n"
"}\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"	background-color: #E59500;\n"
"	color: #840032;\n"
"	border-style: none;\n"
"	border-width: 1px;\n"
"	border-radius: 5px;\n"
"	border-color: ;\n"
"	padding: 10px;\n"
"	font:bold;\n"
"}\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton\n"
"{\n"
"	background-color: #E59500;\n"
"	color: #002642;\n"
"	border-s"
                        "tyle: none;\n"
"	border-width: 1px;\n"
"	border-radius: 5px;\n"
"	border-color: ;\n"
"	padding: 10px;\n"
"	font:bold;\n"
"}\n"
"\n"
"QToolButton::disabled\n"
"{\n"
"	background-color: #ffccd8;\n"
"	color: #E5DADA;\n"
"	border-style: none;\n"
"	border-width: 1px;\n"
"	border-radius: 5px;\n"
"	border-color: ;\n"
"	padding: 10px;\n"
"	font:bold;\n"
"}\n"
"\n"
"QToolButton::hover\n"
"{\n"
"	background-color: #002642;\n"
"	color: #E5DADA;\n"
"	border-style: none;\n"
"	border-width: 1px;\n"
"	border-radius: 5px;\n"
"	border-color: ;\n"
"	padding: 10px;\n"
"	font:bold;\n"
"}\n"
"\n"
"QToolButton::pressed\n"
"{\n"
"	background-color: #002642;\n"
"	color: #840032;\n"
"	border-style: none;\n"
"	border-width: 1px;\n"
"	border-radius: 5px;\n"
"	border-color: ;\n"
"	padding: 10px;\n"
"	font:bold;\n"
"}\n"
"\n"
"/*-----QComboBox-----*/\n"
"\n"
"QComboBox\n"
"{\n"
"    background-color: #E5DADA;\n"
"    border:1px solid black;\n"
"    border-radius:3px;\n"
"    padding:3px;\n"
"    font:bold;    \n"
"    color: #002642;\n"
""
                        "}\n"
"\n"
"QComboBox::hover\n"
"{\n"
"    background-color: #f0f0f0;\n"
"    border:1px solid black;\n"
"    border-radius:3px;\n"
"    font:bold;      \n"
"}\n"
"\n"
"/*-----QSpinBox & QDoubleSpinBox & QDateTimeEdit-----*/\n"
"QSpinBox, \n"
"QDoubleSpinBox,\n"
"QDateTimeEdit\n"
"{\n"
"    background-color: #E5DADA;\n"
"    border:1px solid black;\n"
"    border-radius:3px;\n"
"    padding:3px;\n"
"    font:bold;    \n"
"    color: #002642;\n"
"}\n"
"\n"
"QSpinBox:hover, \n"
"QDoubleSpinBox::hover,\n"
"QDateTimeEdit::hover\n"
"{\n"
"    background-color: #f0f0f0;\n"
"    border:1px solid black;\n"
"    border-radius:3px;\n"
"    padding:3px;\n"
"    font:bold;  \n"
"}\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit,\n"
"QTextEdit\n"
"{\n"
"	background-color: #E5DADA;\n"
"	border:1px solid;\n"
"	border-width: 1px;\n"
"	border-radius: 3px;\n"
"	border-color: #051a39;\n"
"	padding: 3px;\n"
"	color: #002642;\n"
"}\n"
"\n"
"QLineEdit::disabled\n"
"{\n"
"	background-color: #f0f0f0;\n"
"	color: #000;\n"
"	border:1px s"
                        "olid;\n"
"	border-width: 1px;\n"
"	border-radius: 3px;\n"
"	border-color: #051a39;\n"
"	padding: 3px;\n"
"}\n"
"\n"
"QFrame#sidebar\n"
"{\n"
"	background-color: #383838;\n"
"	border-radius: 10px;\n"
"}\n"
"\n"
"/*-----QTabWidget-----*/\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 1px solid #E59500;\n"
"    position: absolute;\n"
"    top: -0.5em;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"	color:#E59500;\n"
"	background-color: #E5DADA;\n"
"	border-style: solid;\n"
"	border-width: 1px;\n"
"	width: 40px;\n"
"	height: 35px;\n"
"	border-top-left-radius: 3px;\n"
"	border-top-right-radius: 3px;\n"
"	border-color: #E59500;\n"
"	padding-bottom: 4px;\n"
"	font-size: 17px;\n"
"	font:bold;\n"
"	\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"	color:#E5DADA;\n"
"	border-style: solid;\n"
"	border-width: 1px;\n"
"	width: 40px;\n"
"	height: 35px;\n"
"	border-top-left-radius: 3px;\n"
"	border-top-right-radius: 3px;\n"
"	border-c"
                        "olor: #E59500;\n"
"	padding-bottom: 0px;\n"
"	font-size: 12px;\n"
"	font:bold;\n"
"	margin-top: 2px;\n"
"}\n"
"\n"
"\n"
"/*-----QProgressBar-----*/\n"
"\n"
"QProgressBar \n"
"{\n"
"    border: 2px solid #E5DADA;\n"
"    border-radius: 10px;\n"
"    padding:2px;\n"
"    text-align: left;\n"
"    margin-left:3em;\n"
"    padding-left:5px;\n"
"    padding-right:5px;\n"
"    font:bold;\n"
"    font-size:20px;\n"
"    height:25px;\n"
"}\n"
"\n"
"QProgressBar::chunk \n"
"{\n"
"    background-color: #840032;\n"
"    width: 10;\n"
"    margin: 0.5px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {  \n"
"    background: #E5DADA;\n"
"    width: 25px;\n"
"    margin: 15px 0 15px 0;\n"
"	border-radius: 10px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {	\n"
"	background-color: #E59500;\n"
"	min-height: 10px;\n"
"	border: solid 2px #E59500;\n"
"	border-radius: 10px;\n"
"}\n"
"QScrollBar::hand"
                        "le:vertical:hover{	\n"
"	background-color: #002642;\n"
"}\n"
"QScrollBar::handle:vertical:pressed {	\n"
"	background-color: #E59500;\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"	border: none;\n"
"	background-color: transparent;\n"
"	height: 20px;\n"
"	border-top-left-radius: 7px;\n"
"	border-top-right-radius: 7px;\n"
"	subcontrol-position: top;\n"
"	subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {	\n"
"	background-color: transparent;\n"
"	height: 0px;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {	\n"
"	background-color: rgb(185, 0, 92);\n"
"    	height: 0px;\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"	border: none;\n"
"	background-color: rgb(59, 59, 90);\n"
"	height: 15px;\n"
"	border-bottom-left-radius: 7px;\n"
"	border-bottom-right-radius: 7px;\n"
"	subcontrol-position: bottom;\n"
"	subcontrol-origin: margin;\n"
"    	height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {	\n"
"	background-color: "
                        "rgb(255, 0, 127);\n"
"    	height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {	\n"
"	background-color: rgb(185, 0, 92);\n"
"    	height: 0px;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"	background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"	background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.button_open_file = QPushButton(self.centralwidget)
        self.button_open_file.setObjectName(u"button_open_file")
        self.button_open_file.setGeometry(QRect(280, 190, 301, 51))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.button_open_file.setText(QCoreApplication.translate("MainWindow", u"Open_File", None))
    # retranslateUi

